# Generated by Django 5.1.7 on 2025-04-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0002_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cor',
            name='nome',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
